AllCops:
  TargetRubyVersion: 1.9

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: semantic
  IgnoredMethods:
    - lambda
    - proc
    - it
    - link

Style/Lambda:
  Enabled: false
  EnforcedStyle: literal

Style/LambdaCall:
  EnforcedStyle: braces

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/PredicateName:
  NameWhitelist:
    - is_a?
    - has_one
    - has_many
